application:
  logo: "JuiceShopCTF_Logo.png"
  favicon: "favicon_ctf.ico"
  showCtfFlagsInNotifications: true
  showChallengeHints: false
  showGitHubRibbon: false
  set NODE_ENV=ctf # on Windows
  export NODE_ENV=ctf # on Linux
  npm start
